export const affiliateTeams = {
  "Anaheim Ducks": "San Diego Gulls",
  "Boston Bruins": "Providence Bruins",
  "Buffalo Sabres": "Rochester Americans",
  "Calgary Flames": "Calgary Wranglers",
  "Carolina Hurricanes": "Chicago Wolves",
  "Chicago Blackhawks": "Rockford IceHogs",
  "Colorado Avalanche": "Colorado Eagles",
  "Columbus Blue Jackets": "Cleveland Monsters",
  "Dallas Stars": "Texas Stars",
  "Detroit Red Wings": "Grand Rapids Griffins",
  "Edmonton Oilers": "Bakersfield Condors",
  "Florida Panthers": "Charlotte Checkers",
  "Los Angeles Kings": "Ontario Reign",
  "Minnesota Wild": "Iowa Wild",
  "Montreal Canadiens": "Laval Rocket",
  "Nashville Predators": "Milwaukee Admirals",
  "New Jersey Devils": "Utica Comets",
  "New York Islanders": "Bridgeport Islanders",
  "New York Rangers": "Hartford Wolf Pack",
  "Ottawa Senators": "Belleville Senators",
  "Philadelphia Flyers": "Lehigh Valley Phantoms",
  "Pittsburgh Penguins": "Wilkes-Barre/Scranton Penguins",
  "San Jose Sharks": "San Jose Barracuda",
  "Seattle Kraken": "Coachella Valley Firebirds",
  "St. Louis Blues": "Springfield Thunderbirds",
  "Tampa Bay Lightning": "Syracuse Crunch",
  "Toronto Maple Leafs": "Toronto Marlies",
  "Utah Mammoth": "Tucson Roadrunners",
  "Vancouver Canucks": "Abbotsford Canucks",
  "Vegas Golden Knights": "Henderson Silver Knights",
  "Washington Capitals": "Hershey Bears",
  "Winnipeg Jets": "Manitoba Moose",
};