ALTER TABLE "Player" 
  ADD COLUMN IF NOT EXISTS "isUfa" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isRfa" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "hasNtc" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isCaptain" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isAssistant" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isRookie" BOOLEAN DEFAULT false;

CREATE TABLE IF NOT EXISTS "Game" (
  "id" SERIAL PRIMARY KEY,
  "homeTeamId" INTEGER NOT NULL REFERENCES "Team"("id"),
  "awayTeamId" INTEGER NOT NULL REFERENCES "Team"("id"),
  "homeScore" INTEGER,
  "awayScore" INTEGER,
  "date" TIMESTAMP NOT NULL,
  "status" TEXT DEFAULT 'scheduled',
  "period" TEXT,
  "timeRemaining" TEXT,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Standing" (
  "id" SERIAL PRIMARY KEY,
  "teamId" INTEGER NOT NULL UNIQUE REFERENCES "Team"("id"),
  "conference" TEXT NOT NULL,
  "division" TEXT,
  "gamesPlayed" INTEGER DEFAULT 0,
  "wins" INTEGER DEFAULT 0,
  "losses" INTEGER DEFAULT 0,
  "otl" INTEGER DEFAULT 0,
  "points" INTEGER DEFAULT 0,
  "goalsFor" INTEGER DEFAULT 0,
  "goalsAgainst" INTEGER DEFAULT 0,
  "season" TEXT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Champion" (
  "id" SERIAL PRIMARY KEY,
  "year" INTEGER NOT NULL,
  "teamId" INTEGER NOT NULL REFERENCES "Team"("id"),
  "gmName" TEXT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Transaction" (
  "id" SERIAL PRIMARY KEY,
  "date" TIMESTAMP NOT NULL,
  "type" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "details" TEXT,
  "season" TEXT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);